version: '3.8'

services:
  deploy:
    image: amazon/aws-cli
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - S3_BUCKET_NAME
    volumes:
      - ./:/aws

